name: iot_scrty
description: "A new Flutter project."
publish_to: 'none'


version: 1.0.0+1

environment:
  sdk: '>=3.2.2 <4.0.0'
  
dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  carousel_slider: ^4.2.1
  mobile_scanner: ^4.0.0
  http: ^1.2.0
  fluttertoast: ^8.2.4
  
dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.1

flutter:
  assets:
    - lib/assets/ueaLogo.jpg
    - lib/assets/informatic_lab.png
    - lib/assets/mori.jpeg
    - lib/assets/guest.png

  uses-material-design: true

 